apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client
  namespace: devops303
subjects:
- kind: User
  name: Client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: client
  apiGroup: rbac.authorization.k8s.io