apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops303
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: ["devops303"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]